name: ormlite-relationships
version: '1.0'
main: me.kodysimpson.ormliterelationships.Relationships
api-version: '1.20'
commands:
  createguild:
    description: creates a new guild
  createachievements:
    description: Creates some achievements